

###
Get http://0.0.0.0:8000/


###
Get http://0.0.0.0:8000/hello/John

###
Post http://0.0.0.0:8000/ask
Content-Type: application/json

{
    "question": "What is the capital of France?",
    "system_prompt": "You are a helpful AI assistant." 
}

###
