

###
Get http://0.0.0.0:8000/


###
Get http://0.0.0.0:8000/hello/John

###
Post http://0.0.0.0:8000/ask
Content-Type: application/json

{
    "question": "hello"
}

###
###
Post http://0.0.0.0:8000/ask
Content-Type: application/json

{
    "question": "How is data stored in milvus?"
}

###
